### ISSUE TITLE
Написать ТЗ

### ISSUE THREAD

**Issue by wldmr-key** [vladislav032/Kursovaya#4]
Напомню, я просил помещать ТЗ в текстовом виде в репозиторий

Цель ты путаешь с назначением и функциями. Следует сформулировать цель создания системы

Характеристика объекта автоматизации (кинотеатра и процесса продажи билетов) отсутствует

Требования к структуре и функционированию системы отсутствуют

Пока все плохо ((

**Comment by vladislav032** [comment]
1.	Техническое задание
1.1. Общие сведения

1.1.1. Полное наименование системы

Онлайн кинотеатр

1.1.2. Наименование организации-заказчика, разработчика системы.

Исполнителем проекта является студент Калужского филиала МГТУ им. Н.Э. Баумана, факультета "Информатика и управление", кафедры ИУК5 "Системы обработки информации", группы ИУК5-51Б, Великий Владислав.
Заказчиком является индивидуальный предприниматель N.

1.1.3. Плановые сроки начала и окончания работы по созданию системы

Систему необходимо разработать в период с 01.09.2022 по 31.11.2022

1.2. Назначение и цели создания системы

1.2.1. Назначение системы

Онлайн кинотеатр предназначен для развлечения и получения досуга от лица клиента.

1.2.2. Цели создания системы

Целью создания онлайн кинотеатра является обеспечение пользователям доступа к уникальному контенту для получения широкого спектра эмоций.


1.3. Характеристика объектов по созданию системы.

Пользователь  выбирает на свой выбор фильм (из имеющихся в базе данных), переходит на страницу просмотра и начинает смотреть готовый после загрузки контент, 

1.4. Требования к системе.

1.4.1. Требования к структуре и функционированию системы.

Система представляет из себя несколько модулей:

- клиентская часть, где клиенты смогут смотреть новинки онлайн кинотеатра или же вбить в поисковой строке нужный фильм который имеется в базе данных, далее клиент может просматривать выбранный им контент.

- администраторская часть, где администраторы смогут добавлять новые фильмы, блокировать клиентов, и просматривать статистику самого кинотеатра.

Создаваемая система должна реализовывать следующие функции:

 - Система должна предоставлять пользователю страницу выбора фильма с сортировкой по категориям или же рейтингу

 - Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)

 - Система должна давать пользователю возможность перехода на страницу просмотра

 - Пользователь может оформлять подписку на просмотр эксклюзивного контента.

У администраторов должна быть возможность:

 - Добавлять/Изменять/Удалять фильмы

 - Добавлять/Изменять категории фильмов

 - Добавлять/Изменять эксклюзивный контент

1.4.2. Требования к численности и квалификации персонала системы и режиму его работы.

Система рассчитана на неограниченное количество пользователей со стороны клиентской части, и одного администратора.

 
1.5. Состав и содержание работ по созданию системы.

- Анализ требований к системе:
Разработчик должен выполнить анализ области применения разрабатываемой системы с точки зрения определения требований к ней.

- Проектирование программной архитектуры:
Разработчик должен определить программную архитектуру, которая описывает общую структуру объекта и определяет компоненты программного объекта.

- Программирование и тестирование программных средств:
Разработчик должен разработать каждый программный модуль и базу данных, а также процедуры испытаний (тестирования) и данные для тестирования каждого программного модуля и базы данных.

1.6. Порядок контроля и приемки системы.

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Все создаваемые программные решения передаются заказчику как в виде готовых модулей, так и в виде исходных кодов, представляемых в электронной форме.

Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.
 
1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие.

Для корректной работы системы, на ПК должен быть доступ в интернет, установлена Windows 10 и выше, а также установлен любой браузер.

1.8. Требования к документированию.

Требуется предоставить:
- Техническое задание в соответствии с ГОСТ 34.602-809
- Расчётно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
то есть, цель создания проекта - филантропическая. Каким способом ты собираешься установить достижимость цели?

**Comment by vladislav032** [comment]
Цель создания проекта является улучшение качества обслуживания пользователя, те сделать сайт более удобный и с меньшей стоимостью подписки. (Надеюсь сейчас все правильно?)

**Comment by wldmr-key** [comment]
зря надеешься. Более удобный, чем что? Как измеряется? С меньшей стоимостью подписки, чем что? Какой профит тому, кто создает и поддерживает сайт?

**Comment by vladislav032** [comment]
цели:
решение проблемы ручного поиска фильма путем добавления поисковой системы на сайт 

создание бесплатной платформы для просмотра фильмов без рекламы

реализация сбора статистики активности пользователей на сайте и ее отображение в панели управления администратора

ликвидация неиспользуемого функционала в виде элементов управления, не придназначенных для поиска и просмотра фильма, реализованного на популярных сайтах для их просмотра

**Comment by wldmr-key** [comment]
))
хотя бы так
пойдет
