### ISSUE TITLE
Концептуальная схема

### ISSUE THREAD

**Issue by vladislav032** [vladislav032/Kursovaya#8]
![КонцSheme drawio (1)](https://user-images.githubusercontent.com/100092864/227898725-4ce10bd6-9b27-46fc-88f1-51dbc7e7aaee.png)

**Comment by wldmr-key** [comment]
Итак, в описании предметной области и требований к системе нет слов "сессия", "план", "время публикации" - дальше стало лениво искать. Так что находи сам

**Comment by vladislav032** [comment]
Поправил исследовательскую часть

**Comment by wldmr-key** [comment]
описание плана - весьма невнятно, там ничего нет про его покупку, и про то, что каждый пользователь получает персональный поименованный план

ты уверен в правильности связи пользователь-избранное? а в остальных?

Еще раз все сам проверь - не трать мое время

**Comment by vladislav032** [comment]
Описание плана исправил
![image](https://user-images.githubusercontent.com/100092864/228071304-c83a0a79-ddb7-4bb5-82b4-7d2d78fa342a.png)

На счет связи пользователь-избранное уверен: у каждого пользователя есть избранное, в котором может находится как минимум один фильм либо не находится вообще
В правильности остальных связей тоже уверен

**Comment by wldmr-key** [comment]
> На счет связи пользователь-избранное уверен: у каждого пользователя есть избранное, в котором может находится как минимум один фильм либо не находится вообще

развею твою уверенность - твоя фраза означает, что в избранном может находиться несколько фильмов, следовательно, это связь один ко многим. 

В свете этого откровения советую пересмотреть тебе все связи. Инача наше общение затянется (я буду находить инциденты по одному)

**Comment by vladislav032** [comment]
![КонцSheme drawio (2)](https://user-images.githubusercontent.com/100092864/228243539-d990ee68-315e-49a8-a75a-8b1cd5f74a98.png)

**Comment by wldmr-key** [comment]
Теперь посмотри на сущность Комментарии - все ли там ладно
И, чтобы два раза не вставать, определись пользователи у тебя сущность или атрибут. И то, и другое не бывает. Ниу кого, кроме тебя (( (касается не только пользователей)

**Comment by vladislav032** [comment]
![КонцSheme drawio (3)](https://user-images.githubusercontent.com/100092864/228358084-5d48739f-8345-42e7-84a6-150d82874d56.png)

**Comment by wldmr-key** [comment]
Теперь посмотри на остальные сущности, как минимум еще одна такая ошибка есть

И, чтобы два раза не вставать, определись, пользователи у тебя сущность или атрибут. И то, и другое не бывает. Ни у кого, кроме тебя (( (касается не только пользователей)

**Comment by vladislav032** [comment]
![КСХ2 drawio](https://user-images.githubusercontent.com/100092864/228636289-6f290d67-0ad5-46bd-8907-43da3e5d31f6.png)

В избраном есть 2 поля, фильм и пользователь, являющиеся одновременно и атрибутами и сущностью

**Comment by wldmr-key** [comment]
> 
> В избраном есть 2 поля, фильм и пользователь, являющиеся одновременно и атрибутами и сущностью

сам-то понял, что написал? к тому же на картинке в избранном нет ничего ))

**Comment by vladislav032** [comment]
Изначально там было 2 поля - фильмы и пользователи , но оставив их будет та самая проблема «сущность превратилась в атрибут хотя она является сущностью» поэтому таблица избранное я оставил пустой

**Comment by wldmr-key** [comment]
а, с чего ты взял, что это сущность?

**Comment by vladislav032** [comment]
Сущность определяется как некоторый обьект рассматриваемой предметной области, информация о котором должна быть отражена в базе данных

Атрибут - это свойтво сущности

Сущности изображаются в виде прямоугольника, атрибуты вписываются внутрь прямоугольника, вот пример:
![image](https://user-images.githubusercontent.com/100092864/228829039-52abbb38-e42b-4bed-b82f-cb0883cd3546.png)
Рис 1. Пример сущности в концептуальной схеме

таким образом, в моей концептульной схеме - фильм или же пользователь , будет являтся сущностью, по критериям приведенными выше
![image](https://user-images.githubusercontent.com/100092864/228829461-28487afa-059c-4eaa-8cdb-0a91d78ebc30.png)
Рис 2. Показ таблицы пользователи
![image](https://user-images.githubusercontent.com/100092864/228829504-ca89f7ea-2e13-49a9-92fa-4868f97f5516.png)
Рис 3. Показ таблицы фильмов

**Comment by vladislav032** [comment]
![КонцСх2 drawio](https://user-images.githubusercontent.com/100092864/228928276-bfd93cbd-bc7b-4ca7-bba4-3f19a3fb367a.png)
Проверьте пожалуйста исправленную схему

**Comment by wldmr-key** [comment]
перед тем как проверять, хотелось бы узнать, как ты ее позиционируешь? на мой взгляд, это ни концептуальная, ни логическая ((

Предыдущая была лучше, ее оставалось приветси в согласованный вид

И, да, ты не ответил на вопрос, чем является, на самом деле, "избранное"?

**Comment by vladislav032** [comment]
Я думаю, что избранное это атрибут для двух сущностей «фильм» и «пользователь»

**Comment by wldmr-key** [comment]
в твоем случае - это просто связь многие ко многим, которая в логической схеме превратится в таблицу

**Comment by vladislav032** [comment]
Получается в моей концептуальной схеме, таблица «избранное»  не нужна?

**Comment by vladislav032** [comment]
Не очень понимаю что такое «согласованный вид», пожалуйста, поясните

**Comment by wldmr-key** [comment]
> Получается в моей концептуальной схеме, таблица «избранное» не нужна?

получается так

**Comment by wldmr-key** [comment]
> Не очень понимаю что такое «согласованный вид», пожалуйста, поясните

согласованный со здравым смыслом

**Comment by vladislav032** [comment]
![22222 drawio (3)](https://user-images.githubusercontent.com/100092864/228989367-7d33edb7-2533-4441-b993-67d74f971dce.png)

**Comment by wldmr-key** [comment]
и, наконец, подписки. В описании предметой области нет понятия "Подписка на сериал". Откуда взялась эта сущность? В схеме у подписки есть атрибут "Эпизод" - это то же, что сущность "Эпизод"?

**Comment by vladislav032** [comment]
![22222 drawio (5)](https://user-images.githubusercontent.com/100092864/229194942-5dd9aa65-e106-490a-9a92-6ab2dc43ea32.png)

Здравстуйте, Владимир Юрьевич! В данной концептуальной схеме была удалина таблица "Подписка на сериал" по причине того, что функционал ее использования не был реализован. Соответственно необходимость описывать таблицу "Подписка на сериал" отсутсвует.

**Comment by wldmr-key** [comment]
в комментарии множественные оценки "нравится" и "не нравится". что это?
В фильме атрибут "количество просмотров" - разве он не рассчитывается. Что такое количество просмотров для сериала?
Что за оценки и комментарии во множественном числе у обзора?

**Comment by vladislav032** [comment]
![22222 drawio (6)](https://user-images.githubusercontent.com/100092864/229361767-4fc05b5d-d161-40f2-ae00-30425d1ca73b.png)

![image](https://user-images.githubusercontent.com/100092864/229361755-86a7174b-a726-422c-ad11-9e14cd64f16a.png)

Сериалов у меня нет.

**Comment by wldmr-key** [comment]
неотвеченные вопросы - 
В фильме атрибут "количество просмотров" - **разве он не рассчитывается?** 
**Что такое количество просмотров для сериала?**

новый вопрос - разве комментарий обзора не является сущностью? Когда атрибут звучит во множественном числе, это всегда подозрительно

**Comment by wldmr-key** [comment]
а-а-а, прочитал "Сериалов у меня нет." - тогда, я не понял смысл понятия эпизоды. Наверное, читал невнимательно. Или давно ))

**Comment by vladislav032** [comment]
Получается атрибуты всегда должны быть в единственном числе ?

**Comment by wldmr-key** [comment]
> Получается атрибуты всегда должны быть в единственном числе ?

не всегда. Но чаще всего

**Comment by vladislav032** [comment]
А с эпизодами напортачил , извиняюсь)

**Comment by vladislav032** [comment]
> неотвеченные вопросы - В фильме атрибут "количество просмотров" - **разве он не рассчитывается?** **Что такое количество просмотров для сериала?**
> 
> новый вопрос - разве комментарий обзора не является сущностью? Когда атрибут звучит во множественном числе, это всегда подозрительно

Количество просмотров рассчитывается скриптом

**Comment by vladislav032** [comment]
![22222 drawio (8)](https://user-images.githubusercontent.com/100092864/229367333-15f24a21-7a19-46c2-a4e5-a2af6525a664.png)

Отсюда удалил эту злащавую таблицу "Эпиозд" так как она не актуальна

**Comment by vladislav032** [comment]
![image](https://user-images.githubusercontent.com/100092864/229367471-b488e676-afa0-4fc2-b3a8-a7de0132d363.png)

В данном куске кода как раз таки и подсчитывается количество просмотров. Атрибут view является тем самым "Количесвтом просмотров" ,а в таблицу tbl_views записывается информация о просмотре

ip получаю здесь 
![image](https://user-images.githubusercontent.com/100092864/229367664-50c7758a-5612-45a5-a113-b4156502c99a.png)

**Comment by wldmr-key** [comment]
первая ошибка:
если делать так, как ты, то эти операции должны быть обернуты в транзакцию (надеюсь, знаешь, что это такое)

вторая ошибка: разве твой views не равен select count(1) from tbl_views where item_id=нужный фильм

**Comment by vladislav032** [comment]
-вторая ошибка: разве твой views не равен select count(1) from tbl_views where item_id=нужный фильм

Таблица tbl_views не связана никак с атрибутом views, в таблицу tbl_views сохраняется вся информация о текущем просмотре.

-если делать так, как ты, то эти операции должны быть обернуты в транзакцию (надеюсь, знаешь, что это такое)

Без понятия что такое транзакция в моем ключе

**Comment by wldmr-key** [comment]
подумай над ответами (и над вопросами,да)

**Comment by vladislav032** [comment]
![image](https://user-images.githubusercontent.com/100092864/229382646-d63f6f7c-6e5e-405c-a95b-b3cf5809bb89.png)
ну вот сделал в $conn->prepare данный запрос "select count(1) from tbl_views where item_id=нужный фильм"

**Comment by vladislav032** [comment]
про обертку транзакции не совсем понял, но почитал статью по этому поводу и сделал так
![image](https://user-images.githubusercontent.com/100092864/229399858-25d6c576-e09c-47d5-9de4-81a6b5014d57.png)

**Comment by wldmr-key** [comment]
> ![image](https://user-images.githubusercontent.com/100092864/229382646-d63f6f7c-6e5e-405c-a95b-b3cf5809bb89.png) ну вот сделал в $conn->prepare данный запрос "select count(1) from tbl_views where item_id=нужный фильм"

пафос моего высказывания заключался в следующем: у тебя в базе данных - дублирование (вещь очень вредная и ее применение нужно обосновывать). Вычисляемую величину (количество просмотров) ты зачем-то еще хранишь

Нужно либо отказаться от дублирования (убрать атрибут "Количество просмотров")
либо, если оно необходимо (зачем?) **весь** свой скрипт (вставку просмотра и изменение количества) заключать в одну транзакцию, чтобы целостность не потерялась

**Comment by vladislav032** [comment]
![22222 drawio (9)](https://user-images.githubusercontent.com/100092864/229485528-038f9b97-c10c-4a6d-8774-ae18fe828ada.png)

**Comment by wldmr-key** [comment]
ох, домучил

логическую-то схему исправишь сам?

**Comment by vladislav032** [comment]
Ну я по концептуальной переделал

![LogicS drawio (12)](https://user-images.githubusercontent.com/100092864/229614177-b691e5d2-428f-4326-a21d-994cd9ed81e0.png)

**Comment by vladislav032** [comment]
Здравствуйте , Владимир Юрьевич. А можно будет все это вам сдать завтра ?

**Comment by wldmr-key** [comment]
Разумеется, сколько ж можно?!
Надеюсь, осилишь все распечатать без ошибок

**Comment by vladislav032** [comment]
Владимир Юрьевич, а вы сегодня в Эвересте? Можно к вам зайти если вы там?
